#!/bin/bash

# Script adapted from https://github.com/tallguyjenks/.dotfiles/blob/master/scripts/.local/bin/statusbar/battery

# Right click for more info
case $BLOCK_BUTTON in
    1) notify-send "Battery" "$(acpi)" --icon= ;;
    3) pgrep -x dunst >/dev/null && notify-send " Battery module" " : discharging
: not charging
: stagnant charge
: charging
: charged
: battery very low!
- Text color reflects charge left" ;;
esac

# Get current battery capacity/status from stdin or default BAT0
battery=/sys/class/power_supply/${1:-BAT0}

# Exit if no battery is found (desktop PCs)
[ ! -d $battery ] && echo "🔌" && exit -1

read -r capacity <"$battery/capacity"
read -r bat_status   <"$battery/status"

# Set the color based on capacity
if [ "$capacity" -ge 85 ]; then
    color="#689d6a"
elif [ "$capacity" -ge 65 ]; then
    color="#fabd2f"
elif [ "$capacity" -ge 50 ]; then
    color="#d79921"
elif [ "$capacity" -ge 25 ]; then
    color="#d65d0e"
elif [ "$capacity" -ge 10 ]; then
    color="#cc241d"
else
    color="#fb4934"
    warn=" "
fi

# If battery below 10 but is now charging remove warning 
[ "$bat_status" = "Chg" ] && warn=""

# If discharging and capacity below 10 then remove status  and replace with warning 
[ "$bat_status" = "Dis" ] && [ -n "$warn" ] && bat_status=""

# if capacity is 0 and battery is not charging then change icon to empty battery and turn off warning
[ "$capacity" = 0 ] && [ "$bat_status" = "Unk" ] && bat_status="" && warn=""

#bat_status="${bat_status//,/}"
bat_status="${bat_status/#Discharging/}"
bat_status="${bat_status/#Not Charging/}"
bat_status="${bat_status/#Charging/}"
bat_status="${bat_status/#Unknown/}"
bat_status="${bat_status/#Full/}"
bat_status="${bat_status} "

# Put it all together
printf "<span color='%s'>%s%s</span>%s\n" "$color" "$bat_status" "$warn" "$capacity%"
