#!/bin/bash

#Mouse actions for the block
case $BLOCK_BUTTON in
    4) brightnessctl s $(echo "$(brightnessctl -q g) + 300" | bc) ;;
    5) brightnessctl s $(echo "$(brightnessctl -q g) - 300" | bc) ;;
esac

brightness=$(echo "100.0 * $(brightnessctl -q g) / $(brightnessctl -q m)" | bc)
brightess=${brightness%.*}
label="<span color='#ccff00'></span>"

echo "$label ${brightness}%"
echo "$label ${brightness}%"
