#!/bin/bash
# Arguments:
# 1: icon
# 2: color

def_icon=
def_col=#fff
source $(dirname $0)/params

#Mouse actions for the block
case $BLOCK_BUTTON in
    4) brightnessctl s $(echo "$(brightnessctl -q g) + 300" | bc) ;;
    5) brightnessctl s $(echo "$(brightnessctl -q g) - 300" | bc) ;;
esac

brightness=$(echo "100.0 * $(brightnessctl -q g) / $(brightnessctl -q m)" | bc)
brightess=${brightness%.*}
label="<span color='$col'>$icon</span>"

echo "$label ${brightness}%"
