#!/bin/sh

#Mouse actions for the block
case $BLOCK_BUTTON in
	1 | 2 | 3)
        notify-send "CPU time (%)" "$(ps axch -o cmd:10,pcpu k -pcpu | head | awk '$0=$0"%"' )"
        ;;
esac

echo " $(grep 'cpu ' /proc/stat | awk '{cpu_usage=($2+$4)*100/($2+$4+$5)} END {printf "%0.2f%", cpu_usage}')   $(sensors | grep temp1 | head -1 | awk '{print $2}')"
