#!/usr/bin/env python3
# coding=utf-8

# Modified by tsagrista, from original source at
# https://github.com/Optixal/i3blocks-crypto
#
# This version needs the cryptocurrency as an argument:
# $  crypto ETH
# $  crypto BTC

# Returns price in EUR instead of USD.
# Also, this script reads your CoinMarketCap API key from .cryptoscript-apikey.txt
# in the same directory.

import json
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import os
import sys

def print_currency(data: list, currency: str):
    base = currency
    quote = data['quote'][base]
    price = float(quote['price'])

    if price > 100: precision = 0
    elif price > 0.1: precision = 2
    else: precision = 6

    percentChange = float(quote['percent_change_' + PRICE_CHANGE_PERIOD])
    percentChangeFormat = '<span color="{}">{}{:.2f}%</span>'
    if percentChange > 0: percentChangeInfo = percentChangeFormat.format('#3BB92D', '▲ ', percentChange)
    elif percentChange == 0: percentChangeInfo = percentChangeFormat.format('#CCCCCC', '', percentChange)
    else: percentChangeInfo = percentChangeFormat.format('#F7555E', '▼ ', percentChange)

    print(('{} {:.' + str(precision) + 'f}€ {}').format(data['symbol'], price, percentChangeInfo)) # Full Text
    print(('{} {:.' + str(precision) + 'f}€').format(data['symbol'], price)) # Short Text

    if percentChange > PRICE_CHANGE_URGENT_PERCENT:
        exit(33)

if len(sys.argv) < 2:
    sys.exit("Error: need 1 parameter:   crypto BTC")

coin_name = sys.argv[1]

base_path = os.path.dirname(os.path.realpath(sys.argv[0]))

with open(base_path + '/.cryptoscript-apikey.txt', 'r') as file:
    filedata = file.read().replace('\n', '')
    API_KEY = filedata
    PRICE_CHANGE_PERIOD = '24h' # Available: '1h', '24h', '7d'
    PRICE_CHANGE_URGENT_PERCENT = 10

    API_URL = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest'

    parameters = {
        'symbol': coin_name,
        'convert': 'EUR'
    }
    headers = {
        'Accepts': 'application/json',
        'X-CMC_PRO_API_KEY': API_KEY,
    }

    session = Session()
    session.headers.update(headers)

    r = session.get(API_URL, params=parameters)
    data = json.loads(r.text)['data']
    data = data[list(data.keys())[0]]

    print_currency(data, 'EUR')
