#!/usr/bin/env bash

#Mouse actions for the block
case $BLOCK_BUTTON in
	1 | 2 | 3)
        (setxkbmap -query | grep -q "layout:\s\+us") && setxkbmap es || setxkbmap us
        ;;
esac
full_path=$(realpath $0)
dir_path=$(dirname $full_path)
echo "<span color='#1990b7'></span> $($dir_path/xkblayout-state print %s)"
echo
