#!/usr/bin/env bash
# Arguments:
# 1: icon
# 2: color

#Mouse actions for the block
case $BLOCK_BUTTON in
	1 | 2 | 3)
        (setxkbmap -query | grep -q "layout:\s\+us") && setxkbmap es || setxkbmap us
        ;;
esac
def_icon=
def_col=#fff
source $(dirname $0)/params

dir_path=$(dirname $0)
echo "<span color='$col'>$icon</span>  $($dir_path/xkblayout-state print %s)"
