#!/bin/sh

case $BLOCK_BUTTON in
	1 | 2 | 3)
        notify-send " Memory hogs (%)" "$(ps axch -o cmd:10,pmem k -pmem | head | awk '$0=$0' )"
        ;;
esac

echo "$(free -h --si | awk '/^Mem:/ {print $3 "/" $2}')"
