#!/bin/sh

DATE=$(date '+%Y-%m-%d')
TIME=$(date '+%H:%M:%S')

echo "<span color='#92d928'></span> $DATE <span color='#92d928'></span> <span font='FiraCode Nerd Font Bold'>$TIME</span>"
echo "<span color='#92d928'></span> $DATE <span color='#92d928'></span> <span font='FiraCode Nerd Font Bold'>$TIME</span>"
