#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
case $BLOCK_BUTTON in
	1) pamixer -t ;;
    2) kitty --class wm-floating pulsemixer ;;
    3) kitty --class wm-floating pulsemixer ;;
	4) pamixer -i 3 ;;
	5) pamixer -d 3 ;;
esac

#Toggle mute
[[ $(pamixer --get-mute) = "true" ]] && echo '婢  0%' && exit
#Display volume
echo 墳 $(pamixer --get-volume)%;
