[[mgr.prepend_keymap]]
on   = [ "l" ]
run  = 'plugin smart-enter'
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
desc = "Mount manager"

[[mgr.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[mgr.append_keymap]]
on   = [ "g", "v" ]
run  = 'cd ~/Videos'
desc = "Go to the ~/Videos directory"

[[mgr.append_keymap]]
on   = [ "g", "p" ]
run  = 'cd ~/Pictures'
desc = "Go to the ~/Pictures directory"

[[mgr.append_keymap]]
on   = [ "g", "b" ]
run  = 'cd ~/.local/share/gaiasky/data'
desc = "Go to the Gaia Sky data directory"

[[mgr.append_keymap]]
on   = [ "b", "g" ]
run  = 'shell "wallpapermgr -s $0" --confirm --orphan'
desc = "Set current image as wallpaper"

[[mgr.append_keymap]]
on   = [ "<C-o>" ]
run  = 'back'
desc = "Go back to the previous directory"

[[mgr.append_keymap]]
on   = [ "<C-i>" ]
run  = 'forward'
desc = "Go forward to the next directory"
