#!/usr/bin/env bash
# Arguments:
# 1: icon
# 2: color

if [[ $XDG_SESSION_TYPE -eq wayland ]]; then
    def_icon=
    def_col=#fff
    source $(dirname $0)/params

    dir_path=$(dirname $0)
    echo "<span color='$col'>$icon</span>  $(swaymsg -t get_inputs | jq -r .[1].xkb_active_layout_name)"

else
    #Mouse actions for the block
    case $BLOCK_BUTTON in
        1 | 2 | 3)
            (setxkbmap -query | grep -q "layout:\s\+us") && setxkbmap es || setxkbmap us
            ;;
    esac
    def_icon=
    def_col=#fff
    source $(dirname $0)/params

    dir_path=$(dirname $0)
    echo "<span color='$col'>$icon</span>  $($dir_path/xkblayout-state print %s)"
fi
